version: '3.4'

services:
  picturestorageservice:
    image: ${DOCKER_REGISTRY-}picturestorageservice
    build:
      context: .
      dockerfile: src/PictureStorageService/Dockerfile
    environment:
      - DB_CONNECTION_STRING=mongodb://user:pass@mongodb/admin
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - db:/data/db
    ports:
      - 27017:27017

volumes:
  db:
