version: '3.4'

services:
  picturestorageservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3000:80"
    volumes:
      - C:\Users\Anirut\Pictures\img-storage:/img-storage
